version: "3.9"

services:
  gateway-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: gateway
    labels:
      - "coolify.name=funstakes-backend-gateway"
      - "traefik.enable=true"
      - "traefik.http.routers.gateway-router.rule=Host(`api.funstakes.net`)"
      - "traefik.http.routers.gateway-router.entrypoints=https"
      - "traefik.http.routers.gateway-router.tls=true"
      - "traefik.http.services.gateway-service.loadbalancer.server.port=8000"
    networks:
      - coolify

  account-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: account-service
    networks:
      - coolify

  post-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: post-service
    networks:
      - coolify

  # Node JS Worker Instance
  node-worker-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: worker-service
        APP_PATH: apps/worker-service/node-worker
    networks:
      - coolify

  # Go Worker Instance
  go-worker-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: go-runner
    networks:
      - coolify

  platform-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: platform-service
    networks:
      - coolify

networks:
  coolify:
    external: true
