# Core Features
Auth:
  - changed-files:
      - any-glob-to-any-file: "frontend/apps/auth/**/*"

Shell:
  - changed-files:
      - any-glob-to-any-file: "frontend/apps/shell/**/*"

Feed:
  - changed-files:
      - any-glob-to-any-file: "frontend/apps/feed/**/*"

Stake:
  - changed-files:
      - any-glob-to-any-file: "frontend/apps/stake/**/*"

Profile:
  - changed-files:
      - any-glob-to-any-file: "frontend/apps/profile/**/*"

Website:
  - changed-files:
      - any-glob-to-any-file: "frontend/apps/website/**/*"

# Infrastructure & Shared
Backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**/*"

Libs:
  - changed-files:
      - any-glob-to-any-file: "frontend/libs/**/*"

# CI/CD Infrastructure
Devops:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
