packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.2
  turbo: ^2.8.10
  prettier: ^3.7.4
  next: ^16.1.6
  eslint: ^9.39.1
  colorthief: ^2.6.0
  idb-keyval: ^6.2.2
  lucide-react: ^0.562.0
  "@types/node": ^22.15.3
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  "@types/colorthief": ^2.6.1
  "@mui/material": ^7.3.7
  "@mui/system": ^6.4.0
  "@mui/icons-material": ^7.3.7
  "@mui/material-nextjs": ^7.3.7
  "@emotion/react": ^11.13.3
  "@emotion/styled": ^11.13.0
  "@emotion/cache": ^11.14.0
  react-transition-group: ^4.4.5
  "@types/react-transition-group": ^4.4.10
  "@vercel/microfrontends": ^2.3.1
  "@tanstack/react-query": ^5.90.21

onlyBuiltDependencies:
  - sharp
