packages:
  - "apps/*"
  - "packages/*"

# This is the "Main" catalog for your logic
catalog:
  # Framework & Database
  express: "^4.19.2"
  mongoose: "^9.2.4"
  mongodb: "^7.1.0"
  dotenv: "^16.4.5"
  cors: "^2.8.5"
  cookie-parser: "^1.4.7"

  # Security
  bcrypt: "^5.1.1"
  jsonwebtoken: "^9.0.2"

  # Services & Utilities
  node-cron: "^4.2.1"
  nodemailer: "^7.0.11"
  resend: "^6.5.2"
  uuid: "^9.0.1"
  "@aws-sdk/client-s3": "^3.1000.0"
  "@aws-sdk/s3-request-presigner": "^3.1000.0"

  # Dev Tools & Build
  typescript: "^5.8.3"
  turbo: "^2.8.16"
  tsc-alias: "^1.8.16"
  tsconfig-paths: "^4.2.0"
  tsx: "^4.19.3"

  # --- ALL TYPES INCLUDED HERE ---
  "@types/node": "^22.15.18"
  "@types/express": "^5.0.1"
  "@types/bcrypt": "^5.0.2"
  "@types/jsonwebtoken": "^9.0.9"
  "@types/cookie-parser": "^1.4.8"
  "@types/cors": "^2.8.18"
  "@types/nodemailer": "^7.0.4"
  "@types/uuid": "^9.0.8"
