export const PLATFORM_ROLES = {
  OWNER: "OWNER",
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  MODERATOR: "MODERATOR",
  SUPPORT: "SUPPORT",
  TRUST_AND_SAFETY: "TRUST_AND_SAFETY",
  FINANCE: "FINANCE",
  ANALYTICS: "ANALYTICS",
  DEVELOPER: "DEVELOPER",
  QA: "QA",
  CONTENT_REVIEWER: "CONTENT_REVIEWER",
} as const;

export type PlatformRole = (typeof PLATFORM_ROLES)[keyof typeof PLATFORM_ROLES];
