export const PLATFORM_ROLES = {
  OWNER: "OWNER",
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  MODERATOR: "MODERATOR",
  SUPPORT: "SUPPORT",
  TRUST_AND_SAFETY: "TRUST_AND_SAFETY",
  FINANCE: "FINANCE",
  ANALYTICS: "ANALYTICS",
  DEVELOPER: "DEVELOPER",
  QA: "QA",
  CONTENT_REVIEWER: "CONTENT_REVIEWER",
} as const;

export const COMMUNITY_ROLES = {
  GUEST: "GUEST",
  USER: "USER",
  VERIFIED_USER: "VERIFIED_USER",
  CREATOR: "CREATOR",
  BUSINESS: "BUSINESS",
  ADVERTISER: "ADVERTISER",
} as const;

export const ROLES = {
  PLATFORM: PLATFORM_ROLES,
  COMMUNITY: COMMUNITY_ROLES,
};
