import { ThemeProvider } from "@mui/material/styles";
import theme from "@/themes/theme";
import CssBaseline from "@mui/material/CssBaseline";
import { ContextProvider } from "./AppContext";
import { AppWrapper } from "./AppWrapper";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  manifest: "/manifest.json",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  icons: {
    icon: "/favicon.ico",
    other: {
      rel: "apple-touch-icon",
      url: "/assets/images/logo.png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@200,300,400,500,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ContextProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <AppWrapper>{children}</AppWrapper>
          </ThemeProvider>
        </ContextProvider>
        <noscript>You need to enable JavaScript to run this app!</noscript>
      </body>
    </html>
  );
}
