"use client";

import { Metadata } from "next";
import { Viewport } from "next";

export const sharedViewport: Viewport = {
  // Set this to your Dark Mode background hex
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#010516" },
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover", // Critical for notched phones (iPhone)
  colorScheme: "dark",
};

export const baseMetadata: Metadata = {
  title: {
    template: "%s | Funstakes",
    default: "Funstakes",
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  manifest: "/manifest.json",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  icons: {
    icon: "/favicon.ico",
    apple: "/logo.png",
  },
};

// export const metadata: Metadata = {
//   title: "Funstakes",
//   description: "Generated by create next app",
//   keywords: ["Next.js", "React", "JavaScript"],
//   manifest: "/manifest.json",
//   generator: "Next.js",
//   applicationName: "Next.js",
//   referrer: "origin-when-cross-origin",
//   icons: {
//     icon: "/favicon.ico",
//     other: {
//       rel: "apple-touch-icon",
//       url: "logo.png",
//     },
//   },
// };
