import { Metadata } from "next";

export const baseMetadata: Metadata = {
  title: {
    template: "%s | Funstakes",
    default: "Funstakes",
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  manifest: "/manifest.json",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  icons: {
    icon: "/favicon.ico",
    apple: "/logo.png",
  },
};

// export const metadata: Metadata = {
//   title: "Funstakes",
//   description: "Generated by create next app",
//   keywords: ["Next.js", "React", "JavaScript"],
//   manifest: "/manifest.json",
//   generator: "Next.js",
//   applicationName: "Next.js",
//   referrer: "origin-when-cross-origin",
//   icons: {
//     icon: "/favicon.ico",
//     other: {
//       rel: "apple-touch-icon",
//       url: "logo.png",
//     },
//   },
// };
