### Variables
@baseUrl = http://localhost:8080/api
@user1ID = 69aa38047ef187d34dba2899
@user1Email = officialblobes6457@gmail.com

### Check Username
POST {{baseUrl}}/auth/check-username
Content-Type: application/json

{
  "username": "fun_staker",
  "useFor": "LOGIN"
}

### Check Email
POST {{baseUrl}}/auth/check-email
Content-Type: application/json

{
  "email": {{user1Email}}
}

### Create an Account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "officialblobes@gmail.com",
  "password": "password123",
  "firstName": "John",
  "lastName": "Doe"
}

### Verify Email Code
POST {{baseUrl}}/auth/verify-email-code
Content-Type: application/json

{
  "email": {{user1Email}},
  "code": "520420"
}

### Resend Email Verification Code
POST {{baseUrl}}/auth/resend-email-code
Content-Type: application/json

{
  "email": {{user1Email}}
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": {{user1Email}},
  "password": "password123"
}

### Verify User Auth
POST {{baseUrl}}/auth/verify-auth
Content-Type: application/json

{
  "email": {{user1Email}}
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json


### Register WhatsApp Number
POST https://graph.facebook.com/v22.0/1078983121959426/messages
Authorization: Bearer EAAM0GyGbxrUBQzEyuKDzcfU1Q7fnZCE3n8XVrOfS8Jo6sdBsgXegMpCwauKkDMhU0vYxnfR7gxPe0uFSQrygCGI0OS4hRPimbLVkZBqGMXQ0T23lH8f49RwkP99GdYALnvjB1uzwP9r7vCFAJ9BNR4e6zdw0C5zldcabQ4QqZA5dPs9X4dAwoZArjrsFYQZDZD
Content-Type: application/json

{
  "messaging_product": "whatsapp",
  "to": "2348057658530",
  "type": "template",
  "template": {
    "name": "update",
    "language": {
      "code": "en_US"
    },
    "components": [
      {
        "type": "body",
        "parameters": [
          {
            "type": "text",
            "text": "123456"
          }
        ]
      },
      {
        "type": "button",
        "sub_type": "url",
        "index": "0",
        "parameters": [
          {
            "type": "text",
            "text": "123456"
          }
        ]
      }
    ]
  }
}